### ISSUE TITLE
[Feature Request] Dynamic size for window titles

### ISSUE THREAD

**Issue by kiarash96** [cedl38/xfce4-windowck-plugin#13] opened 2014-12-28 14:19 UTC
It would be great to have a "dynamic" size option for window titles applet besides "at most" and "fixed" options.

**Comment by cedl38** [comment] 2015-05-17 16:07
There is an "extend" option for that. Such option don't give expecting results in all case for some obscure reasons.. 
However you could use extended separators to simulate dynamic size.

**Comment by cedl38** [comment] 2015-05-21 04:26
Duplicate of  #4

**Closed by cedl38** 2015-05-21 04:26 UTC
